### PR TITLE
update to 4.6.0

### PR DESCRIPTION
**Pull request by grlee77**
the same pypi redirect wasn't working for 4.6.0, so switched to a github link here

### CODE REVIEW

**Comment by jakirkham** [comment]
Please remember to fork, @grlee77 . Making changes to the feedstock results in automatic deployment (even on a non-`master` branch).

**Comment by jakirkham** [comment]
Would actually strongly recommend closing this and reopening a PR from your fork.

**Comment by grlee77** [comment]
This PR is from my fork.  Just prior to that I noticed that had accidentally pushed to a branch directly at the conda-forge feedstock.  I deleted that branch once I realized the mistake.

**Comment by grlee77** [comment]
Do I need to do something else to remove the files that got uploaded at `https://anaconda.org/conda-forge/traits/files` by my mistake?  I see a few linux packages for 4.6.0 there

**Comment by grlee77** [comment]
@jakirkham 
Is this going to cause problems if I merge it due to the already uploaded files?  Would a potential workaround (if we don't remove the ones already uploaded) be to bump the build number here?

**Comment by jakirkham** [comment]
Yep, bumping the build number is perfectly fine solution. 😄

**Pull request merged**
